services:
  express-service:
    build: ./express-service
    container_name: express-service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=7ee4c60b7dd79bc474dca37f4a64e891e696ff0ff5ca950
      - PORT=8000
      - NODE_ENV=developement
      - REDIS_HOST_URL=redis://redis:6379
      - REDIS_HOST=redis
      - MONGODB_HOST_URL=mongodb://mongo:27017
      - HOST_URL=http://localhost:8000/
    depends_on:
      - "redis"
      - "mongodb"
      - "worker-service"

  worker-service:
    build: ./worker-service
    container_name: worker-service
    environment:
      - REDIS_HOST_URL=redis://redis:6379
      - REDIS_HOST=redis
      - MONGODB_HOST_URL=mongodb://mongo:27017
    depends_on:
      - redis
      - mongodb

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - express-service

  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:6"
    container_name: "mongo"
    ports:
      - 5010:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
